#server:
#  port: 8090
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: userModule
#        uri: http://localhost:8091/
#        predicates:
#        - Path=/user/**
#      - id: consumerModule
#        uri: http://localhost:8092/
#        predicates:
#        - Path=/consumer/**