#server:
#  port: 8090
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: userModule
#        uri: http://localhost:8094/
#        predicates:
#          - Path=/user/**
#        filters:
#          - name: JWTFilter
